#!/usr/bin/env perl
# vim: ft=perl

# from: http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen

use strict;
use warnings;

use File::Basename;

my $git_bundles = [ 
  "git://github.com/chrismetcalf/vim-yankring.git",
  "git://github.com/gmarik/snipmate.vim.git",
  "git://github.com/kogakure/vim-sparkup.git",
  "git://github.com/mattn/gist-vim.git",
  "git://github.com/scrooloose/nerdcommenter.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/vim-scripts/L9.git",
  "git://github.com/vim-scripts/FuzzyFinder.git",
  "git://github.com/vim-scripts/Command-T.git",
  "git://github.com/vim-scripts/Haml.git",
  "git://github.com/vim-scripts/Markdown.git",
  "git://github.com/vim-scripts/SuperTab.git",
  "git://github.com/vim-scripts/Zephyr-Color-Scheme.git",
  "git://github.com/vim-scripts/ZoomWin.git",
  "git://github.com/vim-scripts/ack.vim.git",
  "git://github.com/vim-scripts/darkburn.git",
  "git://github.com/vim-scripts/dbext.vim.git",
  "git://github.com/vim-scripts/file-line.git",
  "git://github.com/vim-scripts/fugitive.vim.git",
  "git://github.com/vim-scripts/git.zip.git",
  "git://github.com/vim-scripts/jQuery.git",
  "git://github.com/vim-scripts/mojo.vim.git",
  "git://github.com/vim-scripts/pathogen.vim.git",
  "git://github.com/vim-scripts/perl-support.vim.git",
  "git://github.com/vim-scripts/repeat.vim.git",
  "git://github.com/vim-scripts/surround.vim.git",
  "git://github.com/vim-scripts/taglist.vim.git",
  "git://github.com/vim-scripts/unimpaired.vim.git",
  "git://github.com/garyaj/VimOrganizer.git",
  "git://github.com/vim-scripts/vividchalk.vim.git",
  "git://github.com/vim-scripts/Zenburn.git",
  "git://github.com/garyaj/vim-colors-solarized.git",
  "git://github.com/garyaj/vim-dbgpclient.git",
];

foreach my $url (@$git_bundles) {
  my $dirname = basename($url,qw(.vim .git));
  $dirname =~ s/\.(vim|git|zip)//g;
  warn "* Unpacking $url into $dirname\n";
  my $dir = "vim/bundle/$dirname";
  if (-d $dir) {
    `git checkout ${dirname}_branch`;
    `git pull`;
    `git checkout master`;
    `git merge --squash -s subtree --no-commit ${dirname}_branch`;
  } else {
    `git remote add ${dirname}_remote $url`;
    `git fetch ${dirname}_remote`;
    `git checkout -b ${dirname}_branch ${dirname}_remote/master`;
    `git checkout master`;
    `git read-tree --prefix=${dir}/ -u ${dirname}_branch`;
  }
}
# vi:ai:et:sw=2 ts=2
